// <auto-generated />
using AgendaCompromissos.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaCompromisso.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20191126161808_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaCompromissos.DataContexts.Consultas", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataHoraFinal")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DataHoraInicial")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DataNascimentoPaciente")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeDoPaciente")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("ConsultaId");

                    b.ToTable("Consulta");
                });
#pragma warning restore 612, 618
        }
    }
}
